### ISSUE TITLE
Unable to fetch the system channel configuration

### ISSUE THREAD

**Issue by jorgego11** [IBM-Blockchain/ansible-collection#144]
I have run the playbooks from 1 to 4 successfully.  I have both the endorsing and ordering orgs created fine.  When I run #5 it seems that its unable to read the system channel configuration and returns 
 **"msg": "Could not fetch block from any ordering service node: [Errno 2] No such file or directory: 'peer'"**

**LOGS with -vvv**

Jorges-MBP-2:tutorial jorgego$ docker run --rm -v `pwd`:`pwd` -w `pwd`  mydockerorg/ansible:v1 ansible-playbook 05-add-organization-to-consortium.yml --extra-vars "@ordering-org-vars.yml" -vvv
ansible-playbook 2.9.6
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/.local/lib/python3.8/site-packages/ansible
  executable location = /root/.local/bin/ansible-playbook
  python version = 3.8.2 (default, Feb 29 2020, 17:03:31) [GCC 9.2.0]
No config file found; using defaults
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
yaml declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
[WARNING]: No inventory was parsed, only implicit localhost is available
ini declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
toml declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'

PLAYBOOK: 05-add-organization-to-consortium.yml ********************************
1 plays in 05-add-organization-to-consortium.yml

PLAY [Add the organization to the consortium] **********************************

TASK [Gathering Facts] *********************************************************
task path: /Users/jorgego/Documents/CODE/ansible-collection/ansible-collection/tutorial/05-add-organization-to-consortium.yml:5
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1586267132.0414455-172815879104363 `" && echo ansible-tmp-1586267132.0414455-172815879104363="` echo /root/.ansible/tmp/ansible-tmp-1586267132.0414455-172815879104363 `" ) && sleep 0'
Using module file /root/.local/lib/python3.8/site-packages/ansible/modules/system/setup.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-1pamrwwh4/tmps3ig220a TO /root/.ansible/tmp/ansible-tmp-1586267132.0414455-172815879104363/AnsiballZ_setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1586267132.0414455-172815879104363/ /root/.ansible/tmp/ansible-tmp-1586267132.0414455-172815879104363/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3.8 /root/.ansible/tmp/ansible-tmp-1586267132.0414455-172815879104363/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1586267132.0414455-172815879104363/ > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers

TASK [Get the ordering service information] ************************************
task path: /Users/jorgego/Documents/CODE/ansible-collection/ansible-collection/tutorial/05-add-organization-to-consortium.yml:14
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1586267133.2810874-27056082807253 `" && echo ansible-tmp-1586267133.2810874-27056082807253="` echo /root/.ansible/tmp/ansible-tmp-1586267133.2810874-27056082807253 `" ) && sleep 0'
Using module file /root/.ansible/collections/ansible_collections/ibm/blockchain_platform/plugins/modules/ordering_service_info.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-1pamrwwh4/tmpe14ub6cx TO /root/.ansible/tmp/ansible-tmp-1586267133.2810874-27056082807253/AnsiballZ_ordering_service_info.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1586267133.2810874-27056082807253/ /root/.ansible/tmp/ansible-tmp-1586267133.2810874-27056082807253/AnsiballZ_ordering_service_info.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3.8 /root/.ansible/tmp/ansible-tmp-1586267133.2810874-27056082807253/AnsiballZ_ordering_service_info.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1586267133.2810874-27056082807253/ > /dev/null 2>&1 && sleep 0'
ok: [localhost] => {
    "changed": false,
    "exists": true,
    "invocation": {
        "module_args": {
            "api_authtype": "basic",
            "api_endpoint": "https://ibp-jorge-ibpconsole-console.london02cluster8x32-bd8e586d66eff81119bfe4722b13dbd4-0001.eu-gb.containers.appdomain.cloud",
            "api_key": "kA0yWf7wmtCGBK2y",
            "api_secret": "lTqKEI4d8Vs5Xt2dnMzvj5K2hAxrJ7Z3",
            "api_timeout": 60,
            "api_token_endpoint": "https://iam.cloud.ibm.com/identity/token",
            "name": "Ordering Service",
            "wait_timeout": 60
        }
    },
    "ordering_service": [
        {
            "api_url": "grpcs://ibp-jorge-orderingservicenode1-orderer.london02cluster8x32-bd8e586d66eff81119bfe4722b13dbd4-0001.eu-gb.containers.appdomain.cloud:443",
            "client_tls_cert": null,
            "cluster_id": "zyuhvzxiaz",
            "cluster_name": "Ordering Service",
            "grpcwp_url": "https://ibp-jorge-orderingservicenode1-grpcweb.london02cluster8x32-bd8e586d66eff81119bfe4722b13dbd4-0001.eu-gb.containers.appdomain.cloud:443",
            "location": "ibm_saas",
            "msp_id": "OrdererMSP",
            "name": "Ordering Service_1",
            "operations_url": "https://ibp-jorge-orderingservicenode1-operations.london02cluster8x32-bd8e586d66eff81119bfe4722b13dbd4-0001.eu-gb.containers.appdomain.cloud:443",
            "pem": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIvVENDQWFTZ0F3SUJBZ0lVR2pMNTYxWVQ4bTE3bHA0YUZlM2RTczlqRytrd0NnWUlLb1pJemowRUF3SXcKWFRFTE1Ba0dBMVVFQmhNQ1ZWTXhGekFWQmdOVkJBZ1REazV2Y25Sb0lFTmhjbTlzYVc1aE1SUXdFZ1lEVlFRSwpFd3RJZVhCbGNteGxaR2RsY2pFUE1BMEdBMVVFQ3hNR1JtRmljbWxqTVE0d0RBWURWUVFERXdWMGJITmpZVEFlCkZ3MHlNREEwTURZeU1qTTVNREJhRncwek5UQTBNRE15TWpNNU1EQmFNRjB4Q3pBSkJnTlZCQVlUQWxWVE1SY3cKRlFZRFZRUUlFdzVPYjNKMGFDQkRZWEp2YkdsdVlURVVNQklHQTFVRUNoTUxTSGx3WlhKc1pXUm5aWEl4RHpBTgpCZ05WQkFzVEJrWmhZbkpwWXpFT01Bd0dBMVVFQXhNRmRHeHpZMkV3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPClBRTUJCd05DQUFRUVZiNTUvVDRXL01ZQ2VZWG1rak1rMHo3ODdxMDlYUmhFMWpmcUtiSUxhUHZJbmhFUytIUWQKS0Z0ZEZIdHVUWExUMFc4bE9UNHFOZVdUdlh5ZW5XMnRvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBUVl3RHdZRApWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVW9DNXByRUdNSVM3WW5kRkV1QncwYitGRml2RXdDZ1lJCktvWkl6ajBFQXdJRFJ3QXdSQUlnQ0JVZGZTRndXR29uK2E0TUlDdlJzTi83OUNrckVYeHRQSjZDWis4V3FnOEMKSUM2c2pvOXA3djZmN2trOWJDUHVYUXc3U1hZclcwdzZmWW1EZzUyZ05jU3YKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=",
            "server_tls_cert": null,
            "system_channel_id": "testchainid",
            "tls_cert": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIvVENDQWFTZ0F3SUJBZ0lVR2pMNTYxWVQ4bTE3bHA0YUZlM2RTczlqRytrd0NnWUlLb1pJemowRUF3SXcKWFRFTE1Ba0dBMVVFQmhNQ1ZWTXhGekFWQmdOVkJBZ1REazV2Y25Sb0lFTmhjbTlzYVc1aE1SUXdFZ1lEVlFRSwpFd3RJZVhCbGNteGxaR2RsY2pFUE1BMEdBMVVFQ3hNR1JtRmljbWxqTVE0d0RBWURWUVFERXdWMGJITmpZVEFlCkZ3MHlNREEwTURZeU1qTTVNREJhRncwek5UQTBNRE15TWpNNU1EQmFNRjB4Q3pBSkJnTlZCQVlUQWxWVE1SY3cKRlFZRFZRUUlFdzVPYjNKMGFDQkRZWEp2YkdsdVlURVVNQklHQTFVRUNoTUxTSGx3WlhKc1pXUm5aWEl4RHpBTgpCZ05WQkFzVEJrWmhZbkpwWXpFT01Bd0dBMVVFQXhNRmRHeHpZMkV3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPClBRTUJCd05DQUFRUVZiNTUvVDRXL01ZQ2VZWG1rak1rMHo3ODdxMDlYUmhFMWpmcUtiSUxhUHZJbmhFUytIUWQKS0Z0ZEZIdHVUWExUMFc4bE9UNHFOZVdUdlh5ZW5XMnRvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBUVl3RHdZRApWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVW9DNXByRUdNSVM3WW5kRkV1QncwYitGRml2RXdDZ1lJCktvWkl6ajBFQXdJRFJ3QXdSQUlnQ0JVZGZTRndXR29uK2E0TUlDdlJzTi83OUNrckVYeHRQSjZDWis4V3FnOEMKSUM2c2pvOXA3djZmN2trOWJDUHVYUXc3U1hZclcwdzZmWW1EZzUyZ05jU3YKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=",
            "type": "fabric-orderer"
        }
    ]
}

TASK [Fail if the ordering service does not exist] *****************************
task path: /Users/jorgego/Documents/CODE/ansible-collection/ansible-collection/tutorial/05-add-organization-to-consortium.yml:24
skipping: [localhost] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [Fetch the system channel configuration] **********************************
task path: /Users/jorgego/Documents/CODE/ansible-collection/ansible-collection/tutorial/05-add-organization-to-consortium.yml:29
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1586267138.843576-191266890668459 `" && echo ansible-tmp-1586267138.843576-191266890668459="` echo /root/.ansible/tmp/ansible-tmp-1586267138.843576-191266890668459 `" ) && sleep 0'
Using module file /root/.ansible/collections/ansible_collections/ibm/blockchain_platform/plugins/modules/channel_config.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-1pamrwwh4/tmp0crf87_l TO /root/.ansible/tmp/ansible-tmp-1586267138.843576-191266890668459/AnsiballZ_channel_config.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1586267138.843576-191266890668459/ /root/.ansible/tmp/ansible-tmp-1586267138.843576-191266890668459/AnsiballZ_channel_config.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3.8 /root/.ansible/tmp/ansible-tmp-1586267138.843576-191266890668459/AnsiballZ_channel_config.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1586267138.843576-191266890668459/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_ibm.blockchain_platform.channel_config_payload_vjmcsdeq/ansible_ibm.blockchain_platform.channel_config_payload.zip/ansible_collections/ibm/blockchain_platform/plugins/modules/channel_config.py", line 495, in main
  File "/tmp/ansible_ibm.blockchain_platform.channel_config_payload_vjmcsdeq/ansible_ibm.blockchain_platform.channel_config_payload.zip/ansible_collections/ibm/blockchain_platform/plugins/modules/channel_config.py", line 300, in fetch
  File "/tmp/ansible_ibm.blockchain_platform.channel_config_payload_vjmcsdeq/ansible_ibm.blockchain_platform.channel_config_payload.zip/ansible_collections/ibm/blockchain_platform/plugins/module_utils/ordering_services.py", line 252, in fetch
    raise Exception(f'Could not fetch block from any ordering service node: {last_e}')
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_authtype": "basic",
            "api_endpoint": "https://ibp-jorge-ibpconsole-console.london02cluster8x32-bd8e586d66eff81119bfe4722b13dbd4-0001.eu-gb.containers.appdomain.cloud",
            "api_key": "kA0yWf7wmtCGBK2y",
            "api_secret": "lTqKEI4d8Vs5Xt2dnMzvj5K2hAxrJ7Z3",
            "api_timeout": 60,
            "api_token_endpoint": "https://iam.cloud.ibm.com/identity/token",
            "identity": "Ordering Org Admin.json",
            "msp_id": "OrdererMSP",
            "name": "testchainid",
            "operation": "fetch",
            "ordering_service": "Ordering Service",
            "organizations": null,
            "original": null,
            "path": "original_config.bin",
            "policies": null,
            "updated": null
        }
    },
    "msg": "Could not fetch block from any ordering service node: [Errno 2] No such file or directory: 'peer'"
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0

**Comment by sstone1** [comment]
@jorgego11 all fixed, sorry about that - left the binaries out of the image - can you pull the latest Dockerfile and try again?

**Comment by jorgego11** [comment]
@sstone1 Thanks for the fix.  I am planning to run another end to end run as soon as #146 is fixed.
