### ISSUE TITLE
Unable to import Org using console

### ISSUE THREAD

**Issue by jorgego11** [IBM-Blockchain/ansible-collection#146]
I have two separate consoles with Org1 & Org2 on each.   I have created Org2 endorsing organization using the playbook.  Now,   If I export that Org2 MSP and import that MSP into the IBP console that only has Org1 the console fails with error:   **Required fields are missing.**

UPDATE:     the MSP that is created by Ansible is missing information to the point that IBP does not accept an exported MSP created with Ansible. I did compare two MSP config files (one created with Ansible and other created in the IBP console) and at least the admin credentials were missing on the Ansible one.

**Comment by sstone1** [comment]
OK, seems to be a couple of problems here:

1. The `host_url` property is missing, this is the URL of the console that "owns" the MSP.
2. The `admins` property is an empty array, and needs to contain at least one admin certificate.

**Comment by sstone1** [comment]
@jorgego11 I assume the problem only occurs when you take an organization and import it into IBP using the UI, rather than the Ansible module for importing an organization? That's the only place I see the problem as well.

**Comment by jorgego11** [comment]
> @jorgego11 I assume the problem only occurs when you take an organization and import it into IBP using the UI, rather than the Ansible module for importing an organization? That's the only place I see the problem as well.

That's correct.  Import it into IBP using the IBP Console is the problem
