### ISSUE TITLE
[Discussion] Cleaner way to pass var values

### ISSUE THREAD

**Issue by alxiong** [IBM-Blockchain/ansible-collection#250]
Currently, many variables in the playbook are supplied via `ansible-playbook xxx.yaml --extra-vars "@some_file.yaml"`

Here's a cleaner (arguably better) way:
```yaml
  vars_files:
    - vars/api.yml
    - vars/resources.yml
    - vars/ordering_org.yml
```

While all [different ways](https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#passing-variables-on-the-command-line) are essentially the same, using `vars_files` has the following advantages:
- reusable var declarations -- there are public arguments like `api_endpoint`, `api_key` etc that should be shared across playbooks.
- simpler commands -- just `ansible-playbook xxx.yaml` now
- version controlled record of vars files used -- providing a rough idea of where to find `<DATA_FIELD>` under specified task

_note:_ the actual `var/*.yaml` files should be gitignored in production, but the file name included in the playbook is fine. 

----
_new edit:_ there is one scenario to use `--extra-vars`, when deploying multiple org each of which has the same playbook but different data. 
```sh
for i in $(seq 1 10); do
  ansible-playbook 02-endorsing-org.yaml --extra-vars "@vars/org$i.yaml"
done
```

**Comment by sstone1** [comment]
This is a great idea @alxiong, I wasn't aware you could do this!
