### ISSUE TITLE
[module: peer] missing fluentd resource allocation option

### ISSUE THREAD

**Issue by alxiong** [IBM-Blockchain/ansible-collection#251]
in the current documentation for the [peer module](https://ibm-blockchain.github.io/ansible-collection/modules/peer.html) under the `resource` section, there seems to be only 4 components -- peer, proxy, couchdb and dind.

However, in actual IBP console web portal, there are five configurable options. The missing one is **fluentd** (i.e. the logging container, "Log Collector")

<img width="267" alt="Picture 1" src="https://user-images.githubusercontent.com/20514086/83219712-9d5bc600-a1a3-11ea-9e6f-e4a7c4e12f6f.png">

**Comment by sstone1** [comment]
@alxiong you cannot actually update these fields in the UI:

![Screenshot 2020-06-02 at 10 47 06](https://user-images.githubusercontent.com/7118158/83506001-7ad8ee00-a4be-11ea-8da6-3f4015fc2222.png)

You also cannot update them in the REST API. 

I'll close this; if you need to change this config, you'll need to raise it with the operational tools team so they can expose it through the REST APIs first.
