### ISSUE TITLE
Documentation wrong for Installing the IBM Blockchain Platform on Openshift

### ISSUE THREAD

**Issue by uhaller** [IBM-Blockchain/ansible-collection#325]
I did a first try to install the IBP console on Openshift via Ansible, I hit an issue which is related to this documentation:
https://ibm-blockchain.github.io/ansible-collection/tutorials/installing.html#installing-the-ibm-blockchain-platform
I noticed a wrong setting for install-ibp.yml:
I changed the setting to target: openshift to overcome this issue. 
Can you please check? Thanks.
![Selection_070](https://user-images.githubusercontent.com/54943114/85857556-6389d980-b7ba-11ea-9e83-652abbd33731.png)

**Comment by sstone1** [comment]
Fixed under #325, will publish a release this week.
