### ISSUE TITLE
Installation of IBP console fails on Openshift with Create console

### ISSUE THREAD

**Issue by uhaller** [IBM-Blockchain/ansible-collection#329]
I did a first try to install the console on Openshift via Ansible, playbook ibp-install.yaml failed with:

TASK [console : Create console] **************************************************************************************************************************************************************************************************************
task path: /home/uhaller/.ansible/collections/ansible_collections/ibm/blockchain_platform/roles/console/tasks/openshift/create.yml:89
fatal: [localhost]: FAILED! => {
    "msg": "An unhandled exception occurred while running the lookup plugin 'template'. Error was a <class 'ansible.errors.AnsibleError'>, original message: template error while templating string: tag name expected. String: #\n# SPDX-License-Identifier: Apache-2.0\n#\n---\n{%+ if product_version is version('2.5.0', '>=') %}\napiVersion: ibp.com/v1alpha2\n{%+ else %}\napiVersion: ibp.com/v1alpha1\n{% endif %}\nkind: IBPConsole\nmetadata:\n  name: \"{{ console }}\"\nspec:\n  arch:\n  - \"{{ arch }}\"\n  license: accept\n  serviceAccountName: \"{{ service_account }}\"\n  email: \"{{ console_email }}\"\n  password: \"{{ console_default_password }}\"\n  registryURL: \"{{ image_registry_url }}\"\n{%+ if product_version is version('2.5.0', '>=') %}\n  imagePullSecrets:\n  - \"{{ image_pull_secret }}\"\n{%+ else %}\n  imagePullSecret: \"{{ image_pull_secret }}\"\n{% endif %}\n  networkinfo:\n    domain: \"{{ console_domain }}\"\n  storage:\n    console:\n      class: \"{{ console_storage_class }}\"\n      size: \"{{ console_storage_size }}\"\n{%+ if console_tls_secret is defined %}\n  tlsSecretName: \"{{ console_tls_secret }}\"\n{% endif %}\n{%+ if zones is defined %}\n  clusterdata:\n    zones:\n{%+ for zone in zones %}\n    - \"{{ zone }}\"\n{% endfor %}\n{% endif %}\n{%+ if console_images is defined %}\n  images:\n    {{ console_images | to_nice_yaml(indent=2, width=1024) | indent(4, false) }}\n{% endif %}\n{%+ if console_versions is defined %}\n  versions:\n    {{ console_versions | to_nice_yaml(indent=2, width=1024) | indent(4, false) }}\n{% endif %}\n"
}

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
localhost                  : ok=24   changed=4    unreachable=0    failed=1    skipped=18   rescued=0    ignored=0 

OpenShift Version: 4.3.23
ansible-galaxy collection: ibm.blockchain_platform:0.0.31

I attached the Ansible output.
[uh-install-ibp-err3.log](https://github.com/IBM-Blockchain/ansible-collection/files/4864256/uh-install-ibp-err3.log)

Can you please check?
Thanks.

**Comment by sstone1** [comment]
@uhaller please could you attach:

The playbook you used (with any secret variables redacted)
The command line you used
The output of the following commands:
python --version
ansible --version
pip -v list
pip --version

**Comment by uhaller** [comment]
Please refer to [#328](https://github.com/IBM-Blockchain/ansible-collection/issues/328) for details

**Comment by sstone1** [comment]
I think the fix for this one is to update Jinja2 from the operating system default:

`pip install -U Jinja2`
