### ISSUE TITLE
which IBP ansible collection is preferred to use on IBM cloud

### ISSUE THREAD

**Issue by y0zg** [IBM-Blockchain/ansible-collection#331]
please let me know which galaxy ansible collections are preferred and which should we use for IBM blockchain platform deployment within IBM Cloud

1)
https://galaxy.ansible.com/ibm/blockchain_platform (points to https://ibm-blockchain.github.io/ansible-collection/tutorials/installing.html)

2)
https://galaxy.ansible.com/ibm/blockchain_platform_manager

**Comment by sstone1** [comment]
@y0zg please use option 1 (the Ansible collection). Option 2 is an early version of our Ansible work which is only suitable for development networks, and will likely be phased out at some point.
