### ISSUE TITLE
Expose CA/peer/ordering service versions through roles and tutorial

### ISSUE THREAD

**Issue by uhaller** [IBM-Blockchain/ansible-collection#338]
IBP release 2.5 includes improved usability and security with Hyperledger Fabric v2 by introducing the capability to deploy new peer and ordering nodes based on either Hyperledger Fabric v1.4.7 or v2.1.1.

Would it be possible to configure Hyperledger Fabric v1.4.7 or v2.1.1 in the variable files? (e.g. ordering-org-vars.yml, org1-vars.yml, org2-vars.yml)

**Comment by sstone1** [comment]
You can specify the CA, peer, and ordering service versions using the underlying Ansible modules:

https://ibm-blockchain.github.io/ansible-collection/modules/certificate_authority.html#parameters
https://ibm-blockchain.github.io/ansible-collection/modules/peer.html#parameters
https://ibm-blockchain.github.io/ansible-collection/modules/ordering_service.html#parameters

We should expose these versions through the Ansible roles (`endorsing_organization` and `ordering_organization`).

At that point, the sample playbooks and variable files included in the tutorial could be updated to demonstrate how you specify the versions for these components.
