### ISSUE TITLE
tutorial.sh fails

### ISSUE THREAD

**Issue by uhaller** [IBM-Blockchain/ansible-collection#370]
I created an IBP network successfully by running following scripts:
build_network.sh build
join_network.sh join
deploy_smart_contract.sh

When running the script tutorial.sh I'm getting following issue:

TASK [Import the ordering service] ***********************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Ordering service exists and appears to be managed by this console, refusing to continue"}

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

Can you please check?
Thanks.

**Comment by sstone1** [comment]
@uhaller this script is not documented and is meant to only be run with three separate IBP instances for testing all of the Ansible playbooks in the tutorial in a single go.
