### ISSUE TITLE
install chaincode and peer deletion fail on V2.x

### ISSUE THREAD

**Issue by OniReimu** [IBM-Blockchain/ansible-collection#390]
Operations: just a simple run the tutorial.sh with commenting the export/import things as I had only one instance.

Expected: No failures throughout the script.

Behaviors: 

- Got stuck on 19-install-and-approve-chaincode.yml with the following issue:
`TASK [Install the chaincode on the peer] ***************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to list installed chaincode on peer: Error: unknown command \"lifecycle\" for \"peer\"\nRun 'peer --help' for usage.\n"}`

- Got stuck on 97-delete-endorsing-organization-components.yml --extra-vars '{"import_export_used":true}' with the following issue:
`TASK [ibm.blockchain_platform.endorsing_organization : Delete peer] ************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to get component by ID: HTTP status code 503: b''"}`

**Comment by sstone1** [comment]
@OniReimu for problem 1, you need to install the Fabric v2.x CLI (`peer version` must show `2.x.x`). For problem 2, you have a problem with your IBM Blockchain Platform console (it's returning a HTTP 503 Service Unavailable error), you need to raise an IBM support ticket.

**Comment by OniReimu** [comment]
Just forgot to mention that docker was the environment I'd been using, meaning that we need to have a new Dockerfile for v2.x, too.

**Comment by sstone1** [comment]
Think this is resolved - the latest Dockerfile has the Fabric v2.x binaries.
