### ISSUE TITLE
Request to add retry logic

### ISSUE THREAD

**Issue by gauthampamu** [IBM-Blockchain/ansible-collection#437]
Getting "failed to create new connection: context deadline exceeded' multiple times when running the build_network script. The issue could be addressed by adding retry logic...to some tasks.

16-join-peer-to-channel.yml
05-add-organization-to-consortium.yml
09-join-peer-to-channel.yml
16-join-peer-to-additional-channel.yml
19-install-additional-chaincode.yml
20-instantiate-additional-chaincode.yml

Here is the code, add this to the end of the task. especially task that fetch the channel config block from the orderer or installing chaincode on the peer and also add the properties to the common-vars.yml file

      register: result
      until: result.msg is undefined
      retries: "{{ api_retries }}"
      delay: "{{ api_delay }}"  

#Add to common-vars.yml file
api_retries: "5"
api_delay: "10"

**Comment by sstone1** [comment]
I've added quite a bit of retry code now - as a result, our CI is much, much more reliable. I will keep an eye out for additional problems, but any problems you continue to see please raise new issues containing the error messages that you see (and preferably a stack trace from passing `-vvv` to Ansible).
