### ISSUE TITLE
use ansible to deploy ibm blockchain using OpenShift cluster

### ISSUE THREAD

**Issue by yehia67** [IBM-Blockchain/ansible-collection#448]
Hello,
I am following  these documentations :
1. OpenShift Configuration on [AWS](https://docs.openshift.com/container-platform/4.5/installing/installing_aws/installing-aws-account.html).
2. Deploy IBM blockchain using [ansible](https://cloud.ibm.com/docs/blockchain-sw-25?topic=blockchain-sw-25-ansible-install-ibp).

All command ran successfully without any error. but the routes for ibm blockchain platfomr  keeps loading forever
![Screenshot_from_2020-09-09_16-41-28](https://user-images.githubusercontent.com/21314724/92708082-21eae280-f356-11ea-90c1-0947d1f61f1a.png)

All pods are working

![Screenshot_from_2020-09-09_12-40-49](https://user-images.githubusercontent.com/21314724/92708259-45159200-f356-11ea-9f9f-32dfc35698d6.png)
I  am unable to trace the error, my questions are:
- How to solve the route issue?
- How to trace the error?
- Would reloading and installing IBM Blockchain platform would solve the issue?
Appreciate your replay.

**Comment by sstone1** [comment]
@yehia67 please can you run the following command in the `ibm-platform` project: `oc get ibpconsoles,ibpcas,ibppeers,ibporderers,pods,deployments,services,routes,pvc`

**Comment by yehia67** [comment]
![Screenshot from 2020-10-20 12-49-16](https://user-images.githubusercontent.com/21314724/96576644-c277df00-12d2-11eb-9c40-f7860116bd91.png)

**Comment by sstone1** [comment]
@yehia67 thanks, the console appears to be running, so suspect that Ansible cannot access it for some reason. Please run this command now: `curl -kvvv https://ibmconsole-ibp-console-console.awa.valoro.xyz`

**Comment by yehia67** [comment]
I got this output
```
* Rebuilt URL to: https://ibmconsole-ibp-console-console.awa.valoro.xyz/
* Could not resolve host: ibmconsole-ibp-console-console.awa.valoro.xyz
* Closing connection 0
curl: (6) Could not resolve host: ibmconsole-ibp-console-console.awa.valoro.xyz
```
I tried to change url to curl -kvvv https://ibmconsole-ibp-console.awa.valoro.xyz
but it gave me the same output

**Comment by sstone1** [comment]
@yehia67 okay, that's what I expected. The system running Ansible cannot resolve DNS entries that should map to your Red Hat OpenShift cluster. Is `awa.valoro.xyz` definitely the right domain to use? Do any `*.awa.valoro.xyz` hostnames resolve correctly on this system?

**Comment by yehia67** [comment]
Yes the Openshift dashboard resolve but with unsecured connection

**Comment by yehia67** [comment]
@sstone1  is following this [guide](https://kubernetes.github.io/ingress-nginx/user-guide/tls/#ssl-passthrough) could solve my issue

**Comment by yehia67** [comment]
We don't have any ssl on our cluster could this be the problem? is[ cert-manager ](https://cert-manager.io/docs/installation/openshift/)a good solution for this>

**Comment by sstone1** [comment]
@yehia67 this is a DNS problem; your system cannot resolve the hostname `ibmconsole-ibp-console-console.awa.valoro.xyz` to the IP address of your OpenShift cluster. What is the hostname of the OpenShift dashboard?

I don't believe it's possible to have an OpenShift cluster without SSL. You also do not need to enable SSL passthrough on OpenShift, only Kubernetes.
