### ISSUE TITLE
IBM Blockchain Platform storage limitation

### ISSUE THREAD

**Issue by mmjazzar** [IBM-Blockchain/ansible-collection#459]
Hello,

Based on the [documentation here](https://cloud.ibm.com/docs/blockchain-sw-25?topic=blockchain-sw-25-console-ocp-about) to deploy IBM Blockchain Platform.

Persistent storage is required. Host-local storage volumes are not supported.

My question is, are there any type of limitation on any other types of storage ?

Best

**Comment by sstone1** [comment]
Please find the storage requirements and limitations here:

OpenShift: https://cloud.ibm.com/docs/blockchain-sw-25?topic=blockchain-sw-25-deploy-ocp-getting-started#deploy-ocp-storage
Kubernetes: https://cloud.ibm.com/docs/blockchain-sw-25?topic=blockchain-sw-25-deploy-k8#deploy-k8-storage
