### ISSUE TITLE
Deploying using ansible on aws Openshift cause a Timeout error

### ISSUE THREAD

**Issue by yehia67** [IBM-Blockchain/ansible-collection#470]
Hey,
I am trying to deploy IBM blockchain platform to Openshift deployed on AWS.
I am following this [documentation](https://docs.openshift.com/container-platform/4.3/installing/installing_aws/installing-aws-default.html)   Then deployed the [ansible-playbook](https://ibm-blockchain.github.io/ansible-collection/tutorials/installing.html#installing-the-ibm-blockchain-platform) But It takes too much time then give a timeout error. You can find the logs [here](https://pastebin.pl/view/74fd9d45)

**Comment by sstone1** [comment]
Is this the same problem as #448?
