### ISSUE TITLE
build_network.sh build fails for v2.x

### ISSUE THREAD

**Issue by uhaller** [IBM-Blockchain/ansible-collection#477]
I'm trying to create an IBP network with v2 Peers and Orderers with ansible-collection-0.0.49 on Docker.

When running 'build_network.sh build' from the v2.x directory the script fails with following output:

`[ibp-user@ddee6c622912 v2.x]$ ./build_network.sh build
+ ansible-playbook 01-create-ordering-organization-components.yml
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [Create components for an ordering organization] ****************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [ibm.blockchain_platform.ordering_organization : Fail if API endpoint not specified] ****************************************************************************************************************************************************
skipping: [localhost]

TASK [ibm.blockchain_platform.ordering_organization : Fail if API authentication type not specified] *****************************************************************************************************************************************
skipping: [localhost]

TASK [ibm.blockchain_platform.ordering_organization : Fail if API key not specified] *********************************************************************************************************************************************************
skipping: [localhost]

TASK [ibm.blockchain_platform.ordering_organization : Fail if API secret not specified] ******************************************************************************************************************************************************
skipping: [localhost]

TASK [ibm.blockchain_platform.ordering_organization : Fail if organization name not specified] ***********************************************************************************************************************************************
skipping: [localhost]

TASK [ibm.blockchain_platform.ordering_organization : Create ordering organization] **********************************************************************************************************************************************************
included: /home/ibp-user/.ansible/collections/ansible_collections/ibm/blockchain_platform/roles/ordering_organization/tasks/create.yml for localhost

TASK [ibm.blockchain_platform.ordering_organization : Fail if organization MSP ID not specified] *********************************************************************************************************************************************
skipping: [localhost]

TASK [ibm.blockchain_platform.ordering_organization : Fail if certificate authority admin enrollment ID not specified] ***********************************************************************************************************************
skipping: [localhost]

TASK [ibm.blockchain_platform.ordering_organization : Fail if certificate authority admin enrollment secret not specified] *******************************************************************************************************************
skipping: [localhost]

TASK [ibm.blockchain_platform.ordering_organization : Fail if organization admin enrollment ID not specified] ********************************************************************************************************************************
skipping: [localhost]

TASK [ibm.blockchain_platform.ordering_organization : Fail if organization admin enrollment secret not specified] ****************************************************************************************************************************
skipping: [localhost]

TASK [ibm.blockchain_platform.ordering_organization : Fail if ordering service enrollment ID not specified] **********************************************************************************************************************************
skipping: [localhost]

TASK [ibm.blockchain_platform.ordering_organization : Fail if ordering service enrollment secret not specified] ******************************************************************************************************************************
skipping: [localhost]

TASK [ibm.blockchain_platform.ordering_organization : Create certificate authority] **********************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (semantic_version) on ddee6c622912's Python /usr/bin/python3.8. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1    skipped=12   rescued=0    ignored=0 `

Can you please check? 
Thanks.

**Comment by btl5037** [comment]
Updated the Dockerfile here, as I encountered this as well: #478
