### ISSUE TITLE
"version not valid" error when creating Certificate Authority

### ISSUE THREAD

**Issue by ptippett** [IBM-Blockchain/ansible-collection#509]
Running Ansible scripts against a new IBP production instance on a new IKS 1.1.7.x cluster and get this when trying to create a CA.

`Failed to create certificate authority: HTTP status code 500: {'statusCode': 500, 'msg': {'status': 500, 'message': 'version not valid'}}"}`

I just cloned master on 1/5/2021, so everything (IBP instance, cluster, and Ansible code) is new.

I noticed the following lines were added to the code recently in common-vars.yaml

```
ca_version: ">=1.4,<2.0"
peer_version: ">=2.2,<3.0"
ordering_service_version: ">=2.2,<3.0"
```

And the currently supported CA version in IBP is 1.4.9-3, so that seems correct.

For debug, I commented out those 3 version lines in common-vars.yaml and it was able to continue with creating the CA and other components.

Just so you have the info, I'm using the build.sh script and running it via docker vs having everything locally installed.  So my exact command line is `docker run --rm -v "$PWD:/tutorials" ibmcom/ibp-ansible /tutorials/build_network.sh build`

**Comment by sstone1** [comment]
I assume this is working now @ptippett?

**Comment by ptippett** [comment]
not sure.  It fell off my list.  I'll retry it at some point and reopen if it's an issue.  Given no one else has found it, maybe it's my env.
