### ISSUE TITLE
The latet version 1.1.3 can not be run to setup IBP.

### ISSUE THREAD

**Issue by dongwangdw** [IBM-Blockchain/ansible-collection#586]
When I tried to setup IBP in OCP, with the latest release. I have this error:

```
[WARNING]: Unable to find 'ibpca-crd.yml.j2' in expected paths (use -vvvvv to see paths)
fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'template'. Error was a <class 'ansible.errors.AnsibleError'>, original message: the template file ibpca-crd.yml.j2 could not be found for the lookup"}
```

I inspected the crd role and found that the files in the template dir changes without prefix "ibp". But the names in task still keep this prefix.

The latest commit has fixed this but it is a defect on the release version. Maybe this fix could be backported.
Thanks.

**Comment by mbwhite** [comment]
@dongwangdw you're correct - this has been resolved in the latest code - in the main branch. We need to release a new version of the collection.
