### ISSUE TITLE
Deploy Contracy Playbook does not take care of sequence

### ISSUE THREAD

**Issue by riki95** [IBM-Blockchain/ansible-collection#631]
If I deploy a Chaincode from the IBM VS Code extension, that is taking care of the sequence, meaning that is query the committed chaincode, checking at the sequence number, increase it by 1 and upgrading the contract.

Ansible playbooks are not doing so, but it a small effort to introduce such a thing.
Plugins are using this function yet `committed_chaincodes = peer_connection.query_committed_chaincodes(channel)` so the information is already present. After this command, we know the committed chaincodes and their sequence.

This means that the sequence number can be automated while approving the chaincode for the organization and also for the commit phase.
I am asking to introduce this automated feature because, while using ansible playbooks to deploy SCs, it is very boring to manually upgrade the sequence each time.

**Comment by riki95** [comment]
> 

Greetings @mbwhite , thanks for the PR!
It seems a good improvement actually. We can leverage the `chaincode_list_info` to get the committed chaincodes, look for the one we are uploading, take the sequence number and upgrade it by one.

I would have prefer an automatical increment like the one is doing the VS Code extension, which does not tell to the user the sequence, it does it automatically.

But of course we can implement a small script to do so. Can you please merge it so that we can use it?
Thanks a lot

**Comment by mbwhite** [comment]
Thanks @riki95; will need to add some additional tests etc for this. I would like to see if we can add the auto-increment and was going to look at that today;

**Comment by riki95** [comment]
Awesome, thanks. We look forward to implementing this in our scripts.
Do you have an ETA?

**Comment by mbwhite** [comment]
Start of this week was spent mostly handling the upcoming Fabric 2.5 beta; but would hope to focus on this (and some other Ansible changes) in the coming week.  

If you're able do any early testing that would be appreciated :-) Will keep the PR updated. 

Can always reach me via the Hyperledger Discord forums as well.

**Comment by riki95** [comment]
Thanks for the info. Just added you on discord so we can chat there

**Comment by mbwhite** [comment]
These should now be supported in the v2.0.0-beta
